# Generated by Django 5.0 on 2023-12-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.ImageField(max_length=255, null=True, upload_to='imgs/')),
            ],
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
