# Generated by Django 5.0 on 2024-01-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_image_delete_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(max_length=255, null=True, upload_to='imgs/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя пятнашек'),
        ),
    ]
